language: r
#os:
  #- osx
cache: packages
sudo: false

before_install:
  - tlmgr update --self --all
  - tlmgr install listings
  - tlmgr install latex-extra

addons:
  apt:
    packages:
      - tcl-dev
      - tk-dev
      - texlive-latex-extra
