language: r
#os:
  #- osx
cache: packages
sudo: false

before_install:
  - tlmgr update --self --all
  - tlmgr install listings

addons:
  apt:
    packages:
      - tcl-dev
      - tk-dev
      - texlive-latex-extra

r_github_packages:
  - jimhester/covr
      
warnings_are_errors: false

after_success:
  - Rscript -e 'covr::coveralls()'
